# Generated by Django 5.2.2 on 2025-06-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondesprojetsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar_emoji',
            field=models.CharField(default='👤', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondesprojetsapp.team'),
        ),
    ]
