# Generated by Django 5.2.2 on 2025-06-16 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondesprojetsapp', '0002_remove_member_created_at_remove_member_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gestiondesprojetsapp.team'),
        ),
    ]
